// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopCartAPI.Models;

namespace ShopCartAPI.Migrations
{
    [DbContext(typeof(ProductDetailContext))]
    partial class ProductDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShopCartAPI.Models.ProductDetail", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DataLancamento")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("NomeProduto")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroProduto")
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PrecoProduto")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdProduto");

                    b.ToTable("ProductDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
